services:
    yowking23:
      image: zen:5000/yowking
      cpus: 2
      cpuset: "2,3"
      volumes:
        - cal45:/opt/yowking/calibrations
      env_file: 
        - env/king.env
      container_name: yowking23
      networks:
        - yow
      restart: always
    yowking45:
      image: zen:5000/yowking
      cpus: 2
      cpuset: "4,5"
      volumes:
        - cal45:/opt/yowking/calibrations
      env_file: 
        - env/king.env
      container_name: yowking45
      networks:
        - yow
      restart: always

networks:
  yow:
    external: true

volumes:
  cal45:
    external: true
