version: '3.8'
services:
  nats:
    image: nats:latest
    container_name: nats
    networks: 
      - yow
    command: ["-js", "-auth", "${NATS_TOKEN}"]
    ports:
      - "4222:4222"
      - "8222:8222"
    env_file:
      - nats.env
  yowbot: 
    image: ace:5000/yeoldwiz
    container_name: yowbot
    env_file:
      - yowbot.env
    networks:
      - yow
    depends_on:
      - nats


networks: 
  yow: 
    external: true

volumes:
  cal45:
    external: true

