version: "3"

dotenv:
  - .env

vars:
  DEPS_IMAGE: "yowdeps"
  MAIN_IMAGE_LOCAL: "zen:5000/yowking:latest"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  import:cm:
    desc: Step 1 - Import Chessmaster assets from CM_DIR into assets/cm
    cmds:
      - echo "CM_DIR=${CM_DIR}"
      - test -n "${CM_DIR}"
      - mkdir -p assets/cm/books
      - mkdir -p assets/cm/personalities
      - cp "${CM_DIR}/TheKing350.exe" assets/cm/TheKing350.exe
      - cp -r "${CM_DIR}/Data/Opening Books/"* assets/cm/books/
      - cp -r "${CM_DIR}/Data/Personalities/"* assets/cm/personalities/
      - cd assets/cm/personalities && rm -f *#*
      - cd assets/cm/personalities && mv "Josh - Age 6.CMP" "Josh6.CMP" || true
      - cd assets/cm/personalities && mv "Josh - Age 7.CMP" "Josh7.CMP" || true
      - cd assets/cm/personalities && mv "Josh - Age 8.CMP" "Josh8.CMP" || true
      - cd assets/cm/personalities && mv "Josh - Age 9.CMP" "Josh9.CMP" || true
      - cd assets/cm/personalities && mv "Josh - Age 12.CMP" "Josh12.CMP" || true
      - >
        bash -lc 'hash=$(md5sum assets/cm/personalities/* | awk "{ print \$1 }" | md5sum | head -c 32);
        echo "personalities folder check";
        echo "correct hash: d3ef7f9453b372e094bac18ce262b442";
        echo "actual hash : $hash"'

  build:deps:image:
    desc: Build the dependency-builder image (Dockerfile.dist)
    cmds:
      - docker build -f Dockerfile.dist -t {{.DEPS_IMAGE}} .

  build:deps:dist:
    desc: Build dependency artifacts into root dist/ using Dockerfile.dist
    deps: [build:deps:image]
    cmds:
      - rm -rf dist
      - docker rm -f yowdeps-build || true
      - docker run --name yowdeps-build {{.DEPS_IMAGE}} ./scripts/build-all.sh
      - docker cp yowdeps-build:/build/dist ./dist
      - docker rm yowdeps-build

  gobuild:
    desc: Build enginewrap and kingworker binaries into dist/
    cmds:
      - GOOS=windows GOARCH=386 go build -o dist/enginewrap.exe ./cmd/enginewrap
      - GOOS=linux CGO_ENABLED=0 go build -o dist/kingworker ./cmd/kingworker

  clean:
    desc: Remove root dist/ and generated compose files
    cmds:
      - rm -rf dist
      - rm -f deploy/compose.yowking.yaml

  clean:assets:
    desc: Remove imported Chessmaster assets (assets/cm)
    cmds:
      - rm -rf assets/cm

  clean:images:
    desc: Remove local build helper image/container
    cmds:
      - docker rm -f yowdeps-build || true
      - docker rmi {{.DEPS_IMAGE}} || true

  clean:all:
    desc: Remove dist, generated compose files, imported CM assets, and helper build image/container
    deps: [clean, clean:assets, clean:images]

  build:dist:
    desc: Step 2 - Build full runtime dist/ (deps artifacts + calibrations + Go binaries)
    deps: [build:deps:dist]
    cmds:
      - mkdir -p dist/calibrations
      - cp ../yeoldwiz/yowbot/cals/xps/run1/clockTimes.json dist/calibrations/clockTimes.json
      - task gobuild

  build:image:
    desc: Step 3 - Build the main yowking container image
    deps: [build:dist]
    cmds:
      - docker rm yowking || true
      - docker image rm {{.MAIN_IMAGE_LOCAL}} || true
      - docker build -t {{.MAIN_IMAGE_LOCAL}} .

  dist:
    desc: Alias for build:dist (Step 2)
    cmds:
      - task build:dist

  image:
    desc: Alias for build:image (Step 3)
    cmds:
      - task build:image

  deploy:
    desc: Step 4 (for now) - Deploy one dev worker
    cmds:
      - task deploy:dev

  deploy:dev:
    desc: Start one dev yowking worker from deploy/compose.dev.yaml
    cmds:
      - docker compose --env-file .env -f deploy/compose.dev.yaml up -d

  deploy:dev:down:
    desc: Stop the dev yowking worker compose stack
    cmds:
      - docker compose --env-file .env -f deploy/compose.dev.yaml down

  dev:up:
    desc: Full dev pipeline (import CM assets, build dist, build image, deploy one dev worker)
    cmds:
      - task import:cm
      - task build:image
      - task deploy:dev
