services:
  yowking-prod-random-45:
    image: zen:5000/yowking:prod-random
    cpus: 2
    cpuset: "4,5"
    pids_limit: 8192
    environment:
      WORKER_TAG: zenRandom
      FORCE_RANDOM_ON: "true"
      ENGINE_MOVE_TIMEOUT: ${ENGINE_MOVE_TIMEOUT:-15m}
    volumes:
      - cal45:/opt/yowking/calibrations
    env_file:
      - env/king.env
    container_name: yowking-prod-random-45
    networks:
      - yow
    restart: always

  yowking-prod-random-67:
    image: zen:5000/yowking:prod-random
    cpus: 2
    cpuset: "6,7"
    pids_limit: 8192
    environment:
      WORKER_TAG: zenRandom
      FORCE_RANDOM_ON: "true"
      ENGINE_MOVE_TIMEOUT: ${ENGINE_MOVE_TIMEOUT:-15m}
    volumes:
      - cal45:/opt/yowking/calibrations
    env_file:
      - env/king.env
    container_name: yowking-prod-random-67
    networks:
      - yow
    restart: always

  yowking-prod-random-89:
    image: zen:5000/yowking:prod-random
    cpus: 2
    cpuset: "8,9"
    pids_limit: 8192
    environment:
      WORKER_TAG: zenRandom
      FORCE_RANDOM_ON: "true"
      ENGINE_MOVE_TIMEOUT: ${ENGINE_MOVE_TIMEOUT:-15m}
    volumes:
      - cal45:/opt/yowking/calibrations
    env_file:
      - env/king.env
    container_name: yowking-prod-random-89
    networks:
      - yow
    restart: always

  yowking-prod-random-1011:
    image: zen:5000/yowking:prod-random
    cpus: 2
    cpuset: "10,11"
    pids_limit: 8192
    environment:
      WORKER_TAG: zenRandom
      FORCE_RANDOM_ON: "true"
      ENGINE_MOVE_TIMEOUT: ${ENGINE_MOVE_TIMEOUT:-15m}
    volumes:
      - cal45:/opt/yowking/calibrations
    env_file:
      - env/king.env
    container_name: yowking-prod-random-1011
    networks:
      - yow
    restart: always

  yowking-prod-random-1213:
    image: zen:5000/yowking:prod-random
    cpus: 2
    cpuset: "12,13"
    pids_limit: 8192
    environment:
      WORKER_TAG: zenRandom
      FORCE_RANDOM_ON: "true"
      ENGINE_MOVE_TIMEOUT: ${ENGINE_MOVE_TIMEOUT:-15m}
    volumes:
      - cal45:/opt/yowking/calibrations
    env_file:
      - env/king.env
    container_name: yowking-prod-random-1213
    networks:
      - yow
    restart: always

  yowking-prod-random-1415:
    image: zen:5000/yowking:prod-random
    cpus: 2
    cpuset: "14,15"
    pids_limit: 8192
    environment:
      WORKER_TAG: zenRandom
      FORCE_RANDOM_ON: "true"
      ENGINE_MOVE_TIMEOUT: ${ENGINE_MOVE_TIMEOUT:-15m}
    volumes:
      - cal45:/opt/yowking/calibrations
    env_file:
      - env/king.env
    container_name: yowking-prod-random-1415
    networks:
      - yow
    restart: always

networks:
  yow:
    external: true

volumes:
  cal45:
    external: true
