services:
  kingwc-ace-chaos-1:
    image: zen:5000/yowking-nt:kingwc
    environment:
      NATS_URL: nats://zen:4222
      WORKER_TAG: kingWCAceChaos
      FORCE_RANDOM_ON: "true"
    env_file:
      - env/king.env
    pids_limit: 256
    restart: unless-stopped
    container_name: yowking-kingwc-ace-chaos-1

  kingwc-ace-chaos-2:
    image: zen:5000/yowking-nt:kingwc
    environment:
      NATS_URL: nats://zen:4222
      WORKER_TAG: kingWCAceChaos
      FORCE_RANDOM_ON: "true"
    env_file:
      - env/king.env
    pids_limit: 256
    restart: unless-stopped
    container_name: yowking-kingwc-ace-chaos-2
