name: kingwc

services:
  worker:
    image: zen:5000/yowking-nt:kingwc
    environment:
      NATS_URL: nats://zen:4222
      WORKER_TAG: kingWC
      FORCE_RANDOM_OFF: "true"
    env_file:
      - env/king.env
    pids_limit: 256
    restart: unless-stopped
