apiVersion: v1
kind: Service
metadata:
  name: yowking-service
spec:
  selector:
    name: yowking
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10